apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: knative-samples
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:526fdb25f5c26d25506e88e86f22b122b5d56be7de31091bcb1a46e5e8e50615
---
apiVersion: samples.knative.dev/v1alpha1
kind: SampleSource
metadata:
  name: sample-source
  namespace: knative-samples
spec:
  interval: "10s"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
apiVersion: samples.knative.dev/v1alpha1
kind: SampleSource
metadata:
  name: sample-source-overrides
  namespace: knative-samples
spec:
  interval: "10s"
  ceOverrides:
    extensions:
      foo: bar
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
