# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "knative.dev/test-infra/scripts",
  "knative.dev/test-infra/tools/dep-collector",
]

[[override]]
  name = "k8s.io/klog"
  version = "v0.2.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.4"

[[override]]
  name = "knative.dev/pkg"
  branch = "master"

[[override]]
  name = "cloud.google.com/go"
  revision = "90f2606161ee6a14efe2ca79fc05ac2b8efe250b"

[[constraint]]
  name = "knative.dev/eventing"
  branch = "master"

# Required for opencensus.
[[override]]
  name = "google.golang.org/genproto"
  revision = "357c62f0e4bbba7e6cc403ae09edcf3e2b9028fe"

[[override]]
  name = "go.opencensus.io"
  # Needed because this includes the appropriate version of metricsdata
  version = "v0.22.0"
  
# Required for opencensus.
[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "0.2.0"

# Required for opencensus.
[[override]]
  name="github.com/golang/protobuf"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false
